name: build

on:
  push:
    branches: [ master ]
  schedule:
    - cron: 20 6 * * 4

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout docker-td repository
        uses: actions/checkout@v2
      - name: Clone tdlib/td repository
        run: |
          git clone https://github.com/tdlib/td.git
      - name: Pull knightniwrem/tdlib docker image
        run: |
          docker pull knightniwrem/tdlib
      - name: Conditionally build and publish images
        env:
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          build_and_update_image() {
            docker login -u knightniwrem -p $DOCKER_HUB_ACCESS_TOKEN
            docker build --target builder -t knightniwrem/tdlib .
            docker tag knightniwrem/td:latest knightniwrem/td:$GIT_TD_VERSION
            docker push knightniwrem/td:latest
            docker push knightniwrem/td:$GIT_TD_VERSION

            docker build -t knightniwrem/tdlib-compiled .
            docker tag knightniwrem/tdlib-compiled:latest knightniwrem/tdlib-compiled:$GIT_TD_VERSION
            docker push knightniwrem/tdlib-compiled:latest
            docker push knightniwrem/tdlib-compiled:$GIT_TD_VERSION
          }
          DOCKER_TD_VERSION=$(docker run --entrypoint git knightniwrem/tdlib:latest describe --abbrev=0 --tags | cut -d 'v' -f 2)
          pushd td
          GIT_TD_VERSION=$(git describe --abbrev=0 --tags | cut -d 'v' -f 2)
          popd
          rm -rf td
          [ "$DOCKER_TD_VERSION" == "$GIT_TD_VERSION" ]] || build_and_update_image
